"""
Reporting and communication tools for generating polished Markdown, HTML, and email drafts.
"""

from typing import Dict, Any, List, Optional
from pathlib import Path
import datetime
from taskflow.core.tool import tool
from taskflow import config

@tool(name="export_markdown_report", description="Save a formatted markdown executive report to the reports directory.")
def export_markdown_report(title: str, content: str, filename: str = "report.md") -> str:
    """Exports markdown content with header and timestamp."""
    p = config.REPORTS_DIR / filename
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    header = f"# {title}\n\n*Generated by TaskFlow AI on {timestamp}*\n\n---\n\n"
    full_text = header + content

    with open(p, "w", encoding="utf-8") as f:
        f.write(full_text)

    return f"Report saved successfully to {p}"

@tool(name="export_html_report", description="Save a beautiful standalone HTML dashboard report.")
def export_html_report(title: str, summary: str, details_html: str, filename: str = "report.html") -> str:
    """Generates an attractive dark/light responsive HTML report."""
    p = config.REPORTS_DIR / filename
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title} - TaskFlow AI</title>
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      line-height: 1.6;
      color: #1e293b;
      background: #f8fafc;
      margin: 0;
      padding: 40px 20px;
    }}
    .container {{
      max-width: 900px;
      margin: 0 auto;
      background: #ffffff;
      padding: 40px;
      border-radius: 12px;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
    }}
    .header {{
      border-bottom: 2px solid #e2e8f0;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }}
    h1 {{ color: #0f172a; margin-top: 0; }}
    .badge {{
      display: inline-block;
      padding: 4px 12px;
      background: #e0e7ff;
      color: #3730a3;
      border-radius: 9999px;
      font-size: 0.875rem;
      font-weight: 600;
    }}
    .summary-box {{
      background: #f1f5f9;
      border-left: 4px solid #3b82f6;
      padding: 16px 20px;
      border-radius: 0 8px 8px 0;
      margin-bottom: 30px;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }}
    th, td {{
      padding: 12px;
      border: 1px solid #e2e8f0;
      text-align: left;
    }}
    th {{ background: #f8fafc; font-weight: 600; }}
    .footer {{
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      font-size: 0.85rem;
      color: #64748b;
      display: flex;
      justify-content: space-between;
    }}
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <span class="badge">TaskFlow AI Automated Report</span>
      <h1>{title}</h1>
      <p style="color: #64748b; margin: 5px 0 0 0;">Generated automatically on {timestamp}</p>
    </div>

    <div class="summary-box">
      <h3>Executive Summary</h3>
      <p>{summary}</p>
    </div>

    <div class="details">
      {details_html}
    </div>

    <div class="footer">
      <span>TaskFlow AI Agent Platform</span>
      <span>Status: Verified & Processed</span>
    </div>
  </div>
</body>
</html>"""

    with open(p, "w", encoding="utf-8") as f:
        f.write(html_template)

    return f"HTML Report saved successfully to {p}"

@tool(name="format_email_draft", description="Format a customer or team email response draft.")
def format_email_draft(recipient: str, subject: str, body: str, urgency: str = "Normal", category: str = "Support") -> Dict[str, Any]:
    """Prepares a formatted draft response for human approval or automated dispatch."""
    draft = {
        "recipient": recipient,
        "subject": subject,
        "body": body.strip(),
        "urgency": urgency,
        "category": category,
        "timestamp": datetime.datetime.now().isoformat(),
        "status": "Ready for Review"
    }
    
    # Save draft to reports
    slug = "".join(c for c in subject if c.isalnum() or c in "-_ ")[:30].strip().replace(" ", "_")
    draft_file = config.REPORTS_DIR / f"email_draft_{slug}.json"
    with open(draft_file, "w", encoding="utf-8") as f:
        import json
        json.dump(draft, f, indent=2)

    return draft
